### ISSUE TITLE
class_delete doesn't handle the failure case properly 

### ISSUE THREAD

**Issue by hongsudt** [ohmage/gem#6]
[31] pry(main)> local.class_delete( class_urn: "urn:class:test:955", check_orphan_campaigns: "true")
NoMethodError: undefined method `from_response' for nil:NilClass
from /home/hongsuda/.rvm/gems/ruby-2.1.1/gems/ohmage-0.0.22/lib/ohmage/request.rb:84:in`error'

**Comment by stevenolen** [comment]
`gem install ohmage -v 0.0.23` to ensure you have the version with the fix!
